### ISSUE TITLE
Question : Host name with FromConnectionString

### ISSUE THREAD

**Issue by nishants** [aloneguid/storage#184]
I am using Azure Blob in production and trying to set up my docker-compose for dev/test environments.

I am running my emulator as a docker container using an image : [https://github.com/azure/azurite](https://github.com/azure/azurite)

I can't find in docs how to use the hostname/port while creating a connection string.

I am trying for something like :
`StorageFactory.Blobs.FromConnectionString("azure.blobs://emulator:10000/development=true")` 

Here is a sample docker-compose:
```
version: '3'

services:
  service:
    build:
      context: .
    ports:
      - "5000:5000"
    depends_on:
      - storage-emulator

 emulator:
    image: "mcr.microsoft.com/azure-storage/azurite"
    ports:
      - "10000:10000"
    command:
      - azurite-blob
      - --blobHost
      - 0.0.0.0
```
